[package]
name = "aardvark_ffi"
version = "0.1.0"
edition = "2021"
links = "aardvark"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.68.1"
